version: '3'

services:

  etebase:
    image: victorrds/etesync:alpine
    restart: always
    volumes:
      - etebase-data:/data:rw
    networks:
      - web
    environment:
      SERVER: http-socket
      SUPER_USER: admin
      SUPER_PASS_FILE: /run/secrets/etebase_admin-password
      DB_ENGINE: sqlite
      ALLOWED_HOSTS: ${DOMAINS_ETEBASE}.${DOMAINS_BASE},www.${DOMAINS_ETEBASE}.${DOMAINS_BASE}
    secrets:
      - etebase_admin-password
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.etebase-web.loadbalancer.server.url=http://etebase:3735"
      # HTTP
      - "traefik.http.routers.etebase-web.rule=Host(`${DOMAINS_ETEBASE}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_ETEBASE}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.etebase-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.etebase-secured.rule=Host(`${DOMAINS_ETEBASE}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_ETEBASE}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.etebase-secured.entrypoints=web-secured"
      - "traefik.http.routers.etebase-secured.tls.certresolver=tlschallenge"
      # Homepage
      - homepage.group=Produktivität
      - homepage.name=Etebase
      - homepage.icon=/icons/etebase.svg
      - homepage.href=https://${DOMAINS_ETEBASE}.${DOMAINS_BASE}
      - homepage.description=Kalender-, Aufgaben und Kontaktesynchronisierung

networks:
  web:
    external: true

volumes:
  etebase-data:

secrets:
  etebase_admin-password:
    file: ../secrets/etebase_admin-password
