services:

  ocis:
    image: owncloud/ocis:7
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - web
      - tika
      - office
    depends_on:
      - tika
    entrypoint: "/custom-entrypoint.sh"
    secrets:
      - ocis_idm-admin-password
    volumes:
      - ./config/ocis/scripts/inject-secrets.sh:/custom-entrypoint.sh
      - ./config/ocis/app-registry.yaml:/etc/ocis/app-registry.yaml:ro
      - ocis-config:/etc/ocis
      - ocis-data:/var/lib/ocis
    environment:
      - PROXY_TLS=false
      - OCIS_INSECURE=false
      - OCIS_CONFIG_DIR=/etc/ocis/
      - OCIS_LOG_LEVEL=warning
      - OCIS_DOMAIN=${DOMAINS_OCIS}.${DOMAINS_BASE}
      - OCIS_URL=https://${DOMAINS_OCIS}.${DOMAINS_BASE}
      - SEARCH_EXTRACTOR_TYPE=tika
      - SEARCH_EXTRACTOR_TIKA_TIKA_URL=http://tika:9998
      - FRONTEND_FULL_TEXT_SEARCH_ENABLED=true
      - IDM_CREATE_DEMO_USERS=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.ocis-web.loadbalancer.server.url=http://ocis:9200"
      # HTTP
      - "traefik.http.routers.ocis-web.rule=Host(`${DOMAINS_OCIS}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.ocis-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.ocis-secured.rule=Host(`${DOMAINS_OCIS}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.ocis-secured.entrypoints=web-secured"
      - "traefik.http.routers.ocis-secured.tls.certresolver=tlschallenge"
      # Homepage
      - homepage.group=Produktivität
      - homepage.name=Cloud
      - homepage.icon=/icons/ocis.svg
      - homepage.href=https://${DOMAINS_OCIS}.${DOMAINS_BASE}
      - homepage.description=Online-Speicher


  # ---------------------------------
  # SEARCH
  # ---------------------------------

  # Used for extracting file contents for search
  tika:
    image: apache/tika:latest-full
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - tika


  # ---------------------------------
  # OFFICE
  # ---------------------------------

  collaboration-oo:
    image: owncloud/ocis:7
    networks:
      - office
    depends_on:
      ocis:
        condition: service_started
      onlyoffice:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: [ "-c", "ocis collaboration server" ]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "ocis:9233"
      COLLABORATION_WOPI_SRC: https://wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}
      COLLABORATION_APP_NAME: "OnlyOffice"
      COLLABORATION_APP_PRODUCT: "OnlyOffice"
      COLLABORATION_APP_ADDR: https://wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}
      COLLABORATION_APP_ICON: https://wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}/web-apps/apps/documenteditor/main/resources/img/favicon.ico
      COLLABORATION_APP_INSECURE: "${INSECURE:-true}"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "${INSECURE:-true}"
      COLLABORATION_LOG_LEVEL: ${LOG_LEVEL:-info}
      COLLABORATION_APP_PROOF_DISABLE: "true"
      OCIS_URL: https://${DOMAINS_OCIS}.${DOMAINS_BASE}
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - ocis-config:/etc/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaboration-oo.entrypoints=web-secured"
      - "traefik.http.routers.collaboration-oo.rule=Host(`wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.collaboration-oo.tls.certresolver=http"
      - "traefik.http.routers.collaboration-oo.service=collaboration-oo"
      - "traefik.http.services.collaboration-oo.loadbalancer.server.port=9300"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

  # Onlyoffice - Web Office
  onlyoffice:
    image: onlyoffice/documentserver:8.2
    restart: always
    logging:
      options:
        max-size: 50m
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    networks:
      - office
    environment:
      - WOPI_ENABLED=true
      - USE_UNAUTHORIZED_STORAGE=false
    volumes:
      - ./config/onlyoffice/entrypoint-override.sh:/entrypoint-override.sh
      - ./config/onlyoffice/local.json:/etc/onlyoffice/documentserver/local.dist.json
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.onlyoffice.loadbalancer.server.url=http://onlyoffice:80"
      # HTTPS
      - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.onlyoffice.entrypoints=web-secured"
      - "traefik.http.routers.onlyoffice.tls.certresolver=tlschallenge"
      # Without this, websockets don't work
      - "traefik.http.middlewares.onlyoffice.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice"
      # Homepage
      - homepage.group=Server-Management
      - homepage.name=Cloud - Onlyoffice
      - homepage.icon=si-onlyoffice
      - homepage.description=Office-Programme im Browser

networks:
  web:
    external: true
  tika:
  office:

volumes:
  ocis-config:
  ocis-data:
  wopi-recovery:

secrets:
  ocis_idm-admin-password:
    file: ../secrets/ocis_idm-admin-password
  ocis_wopi_secret:
    file: ../secrets/ocis_wopi-secret
