version: "3"

services:

  ocis:
    image: owncloud/ocis:6
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - web
      - tika
      - office
    depends_on:
      - tika
      - ocis-appprovider-onlyoffice
    entrypoint: "/custom-entrypoint.sh"
    secrets:
      - ocis_idm-admin-password
    volumes:
      - ./config/ocis/scripts/inject-secrets.sh:/custom-entrypoint.sh
      - ./config/ocis/app-registry.yaml:/etc/ocis/app-registry.yaml:ro
      - ocis-config:/etc/ocis
      - ocis-data:/var/lib/ocis
    environment:
      - PROXY_TLS=false
      - OCIS_INSECURE=false
      - OCIS_CONFIG_DIR=/etc/ocis/
      - OCIS_LOG_LEVEL=warning
      - OCIS_DOMAIN=${DOMAINS_OCIS}.${DOMAINS_BASE}
      - OCIS_URL=https://${DOMAINS_OCIS}.${DOMAINS_BASE}
      - SEARCH_EXTRACTOR_TYPE=tika
      - SEARCH_EXTRACTOR_TIKA_TIKA_URL=http://tika:9998
      - FRONTEND_FULL_TEXT_SEARCH_ENABLED=true
      - IDM_CREATE_DEMO_USERS=false
      - OCIS_SERVICE_ACCOUNT_ID=service-admin
      - OCIS_SERVICE_ACCOUNT_SECRET=${OCIS_SERVICE_ACCOUNT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.ocis-web.loadbalancer.server.url=http://ocis:9200"
      # HTTP
      - "traefik.http.routers.ocis-web.rule=Host(`${DOMAINS_OCIS}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.ocis-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.ocis-secured.rule=Host(`${DOMAINS_OCIS}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.ocis-secured.entrypoints=web-secured"
      - "traefik.http.routers.ocis-secured.tls.certresolver=tlschallenge"
      # Homepage
      - homepage.group=Produktivität
      - homepage.name=Cloud
      - homepage.icon=/icons/ocis.svg
      - homepage.href=https://${DOMAINS_OCIS}.${DOMAINS_BASE}
      - homepage.description=Online-Speicher


  # ---------------------------------
  # SEARCH
  # ---------------------------------

  # Used for extracting file contents for search
  tika:
    image: apache/tika:latest-full
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - tika


  # ---------------------------------
  # OFFICE
  # ---------------------------------

  wopiserver:
    image: cs3org/wopiserver:${WOPISERVER_DOCKER_TAG:-v10.1.0}
    networks:
      - office
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    environment:
      WOPISERVER_DOMAIN: wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}
    secrets:
      - ocis_wopi_secret
    volumes:
      - ./config/wopiserver/entrypoint-override.sh:/entrypoint-override.sh:ro
      - ./config/wopiserver/wopiserver.conf.dist:/etc/wopi/wopiserver.conf.dist:ro
      - wopi-recovery:/var/spool/wopirecovery
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.wopiserver-web.loadbalancer.server.url=http://wopiserver:8800"
      # HTTP
      - "traefik.http.routers.wopiserver-web.rule=Host(`wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.wopiserver-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.wopiserver-secured.rule=Host(`wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.wopiserver-secured.entrypoints=web-secured"
      - "traefik.http.routers.wopiserver-secured.tls.certresolver=tlschallenge"
      # Homepage
      - homepage.group=Server-Management
      - homepage.name=Cloud - Wopi-Server
      - homepage.icon=mdi-server-outline
      - homepage.description=Office-Connector zwischen Cloud und Onlyoffice

  ocis-appprovider-onlyoffice:
    image: owncloud/ocis:6
    restart: always
    logging:
      options:
        max-size: 50m
    user: "0"
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    depends_on:
      - onlyoffice
      - wopiserver
    networks:
      - office
    environment:
      # use the internal service name of the gateway
      REVA_GATEWAY: com.owncloud.api.gateway
      APP_PROVIDER_GRPC_ADDR: 0.0.0.0:9164
      APP_PROVIDER_SERVICE_NAME: app-provider-onlyoffice
      # use the internal service name
      APP_PROVIDER_EXTERNAL_ADDR: com.owncloud.api.app-provider-onlyoffice
      APP_PROVIDER_DRIVER: wopi
      APP_PROVIDER_WOPI_APP_NAME: OnlyOffice
      APP_PROVIDER_WOPI_APP_ICON_URI: https://onlyoffice.${DOMAINS_OCIS}.${DOMAINS_BASE}/web-apps/apps/documenteditor/main/resources/img/favicon.ico
      APP_PROVIDER_WOPI_APP_URL: https://onlyoffice.${DOMAINS_OCIS}.${DOMAINS_BASE}
      APP_PROVIDER_WOPI_INSECURE: "${INSECURE:-false}"
      APP_PROVIDER_WOPI_WOPI_SERVER_EXTERNAL_URL: https://wopiserver.${DOMAINS_OCIS}.${DOMAINS_BASE}
      APP_PROVIDER_WOPI_FOLDER_URL_BASE_URL: https://${DOMAINS_OCIS}.${DOMAINS_BASE}
      # share the registry with the ocis container
      MICRO_REGISTRY: "mdns"
      OCIS_SERVICE_ACCOUNT_ID: service-admin
      OCIS_SERVICE_ACCOUNT_SECRET: ${OCIS_SERVICE_ACCOUNT_SECRET}
    volumes:
      - ./config/ocis-appprovider-onlyoffice/entrypoint-override.sh:/entrypoint-override.sh:ro
      - ocis-config:/etc/ocis

  # Onlyoffice - Web Office
  onlyoffice:
    image: onlyoffice/documentserver:7.5
    restart: always
    logging:
      options:
        max-size: 50m
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    networks:
      - office
    environment:
      - WOPI_ENABLED=true
      - USE_UNAUTHORIZED_STORAGE=false
    volumes:
      - ./config/onlyoffice/entrypoint-override.sh:/entrypoint-override.sh
      - ./config/onlyoffice/local.json:/etc/onlyoffice/documentserver/local.dist.json
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.onlyoffice-web.loadbalancer.server.url=http://onlyoffice:80"
      # HTTP
      - "traefik.http.routers.onlyoffice-web.rule=Host(`onlyoffice.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.onlyoffice-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.onlyoffice-secured.rule=Host(`onlyoffice.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.onlyoffice-secured.entrypoints=web-secured"
      - "traefik.http.routers.onlyoffice-secured.tls.certresolver=tlschallenge"
      # Without this, websockets don't work
      - "traefik.http.middlewares.onlyoffice.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.onlyoffice-secured.middlewares=onlyoffice"
      # Homepage
      - homepage.group=Server-Management
      - homepage.name=Cloud - Onlyoffice
      - homepage.icon=si-onlyoffice
      - homepage.description=Office-Programme im Browser

networks:
  web:
    external: true
  tika:
  office:

volumes:
  ocis-config:
  ocis-data:
  wopi-recovery:

secrets:
  ocis_idm-admin-password:
    file: ../secrets/ocis_idm-admin-password
  ocis_wopi_secret:
    file: ../secrets/ocis_wopi_secret
