services:

  vaultwarden:
    depends_on:
      - db
    image: vaultwarden/server:latest
    volumes:
      - vaultwarden:/data/
    restart: always
    networks:
      - web
      - db
    logging:
      options:
        max-size: 50m
    environment:
      SIGNUPS_ALLOWED: false
      SHOW_PASSWORD_HINT: false
      DATABASE_URL: 'postgresql://vaultwarden:vaultwarden@db/vaultwarden'
      SMTP_HOST_FILE: /run/secrets/mail_smtp_host
      SMTP_FROM_FILE: /run/secrets/mail_smtp_from
      SMTP_PORT_FILE: /run/secrets/mail_smtp_port
      SMTP_SECURITY_FILE: /run/secrets/mail_smtp_security
      SMTP_USERNAME_FILE: /run/secrets/mail_smtp_username
      SMTP_PASSWORD_FILE: /run/secrets/mail_smtp_password
      ADMIN_TOKEN_FILE: /run/secrets/vaultwarden_admin-token
      DOMAIN: https://${DOMAINS_VAULTWARDEN}.${DOMAINS_BASE}
    secrets:
      - mail_smtp_host
      - mail_smtp_from
      - mail_smtp_port
      - mail_smtp_security
      - mail_smtp_username
      - mail_smtp_password
      - vaultwarden_admin-token
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.vaultwarden-web.loadbalancer.server.url=http://vaultwarden:80"
      # HTTP
      - "traefik.http.routers.vaultwarden-web.rule=Host(`${DOMAINS_VAULTWARDEN}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_VAULTWARDEN}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.vaultwarden-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.vaultwarden-secured.rule=Host(`${DOMAINS_VAULTWARDEN}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_VAULTWARDEN}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.vaultwarden-secured.entrypoints=web-secured"
      - "traefik.http.routers.vaultwarden-secured.tls.certresolver=tlschallenge"
      # Security Headers
      - "traefik.http.middlewares.vaultwardenHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.vaultwardenHeaders.headers.browserxssfilter=true"
      # Apply headers
      - traefik.http.routers.vaultwarden-secured.middlewares=vaultwardenHeaders
      # Homepage
      - homepage.group=Produktivität
      - homepage.name=Vault
      - homepage.icon=/icons/vaultwarden.svg
      - homepage.href=https://${DOMAINS_VAULTWARDEN}.${DOMAINS_BASE}
      - homepage.description=Passwortmanager

  db:
    image: postgres:14-alpine
    restart: always
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 20m
    environment:
      POSTGRES_USER: vaultwarden
      POSTGRES_PASSWORD: vaultwarden
      POSTGRES_DB: vaultwarden

volumes:
  vaultwarden:
  db:

networks:
  web:
    external: true
  db:

secrets:
  mail_smtp_host:
    file: ../secrets/mail_smtp_host
  mail_smtp_from:
    file: ../secrets/mail_smtp_from
  mail_smtp_port:
    file: ../secrets/mail_smtp_port
  mail_smtp_security:
    file: ../secrets/mail_smtp_security
  mail_smtp_username:
    file: ../secrets/mail_smtp_username
  mail_smtp_password:
    file: ../secrets/mail_smtp_password
  vaultwarden_admin-token:
    file: ../secrets/vaultwarden_admin-token