services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    networks:
      - web
    logging:
      options:
        max-size: 50m
    environment:
      HOMEPAGE_VAR_BASEURL: https://${DOMAINS_BASE}
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAINS_BASE}
    volumes:
      - ./config/homepage/config/bookmarks.yml:/app/config/bookmarks.yaml
      - ./config/homepage/config/docker.yml:/app/config/docker.yaml
      - ./config/homepage/config/services.yml:/app/config/services.yaml
      - ./config/homepage/config/settings.yml:/app/config/settings.yaml
      - ./config/homepage/config/widgets.yml:/app/config/widgets.yaml
      - ./config/homepage/public/icons:/app/public/icons:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.homepage-web.loadbalancer.server.url=http://homepage:3000"
      # HTTP
      - "traefik.http.routers.homepage-web.rule=Host(`${DOMAINS_BASE}`) || Host(`www.${DOMAINS_BASE}`)"
      - "traefik.http.routers.homepage-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.homepage-secured.rule=Host(`${DOMAINS_BASE}`) || Host(`www.${DOMAINS_BASE}`)"
      - "traefik.http.routers.homepage-secured.entrypoints=web-secured"
      - "traefik.http.routers.homepage-secured.tls.certresolver=tlschallenge"
      # Security Headers
      - "traefik.http.middlewares.homepage-headers.headers.contentSecurityPolicy=default-src 'self'; img-src 'self' cdn.jsdelivr.net"
      # Apply headers
      - traefik.http.routers.homepage-web.middlewares=homepage-headers
      - traefik.http.routers.homepage-secured.middlewares=homepage-headers
      # Homepage
      - homepage.group=Server-Management
      - homepage.name=Homepage
      - homepage.href=https://${DOMAINS_BASE}
      - homepage.description=Diese Dashboard-Seite
      - homepage.icon=si-homepage

networks:
  web:
    external: true