services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: ${HOSTNAME}
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - web
    environment:
      NETDATA_CLAIM_URL: https://app.netdata.cloud
      NETDATA_CLAIM_TOKEN: ${NETDATA_CLAIM_TOKEN}
      NETDATA_CLAIM_ROOMS: ${NETDATA_CLAIM_ROOMS}
    volumes:
      - ./netdataconfig/netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    logging:
      options:
        max-size: 100m
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.netdata-web.loadbalancer.server.url=http://netdata:19999"
      # HTTPS
      - "traefik.http.routers.netdata-secured.rule=Host(`${DOMAINS_NETDATA}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.netdata-secured.entrypoints=web-secured"
      - "traefik.http.routers.netdata-secured.tls.certresolver=tlschallenge"
      # Auth
      - "traefik.http.middlewares.netdata-auth.basicauth.users=admin:${PASSWORD}"
      - "traefik.http.routers.netdata-secured.middlewares=netdata-auth"
      # Homepage
      - homepage.group=Server-Management
      - homepage.name=Netdata
      - homepage.description=Monitoring
      - homepage.icon=si-netdata

networks:
  web:
    external: true

volumes:
  netdatalib:
  netdatacache: